In [3]:
import tensorflow as tf
import numpy as np

In [5]:
tf.set_random_seed(777)  # for reproducibility

x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5],
          [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0],
          [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

# Evaluation our model using this test dataset
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]




In [6]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])
W = tf.Variable(tf.random_normal([3,3]), name = 'weight')
b = tf.Variable(tf.random_normal([3]), name = 'bias')

In [19]:
hypo = tf.nn.softmax(tf.matmul(X,W) + b)
cost = tf.reduce_mean(-tf.reduce_sum(Y*tf.log(hypo), axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.001).minimize(cost)

In [9]:
pred = tf.arg_max(hypo, 1)
is_correct = tf.equal(pred, tf.arg_max(Y,1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [20]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2000):
        cost_val, W_val, _ = sess.run([cost, W, optimizer],
                                     feed_dict={X:x_data, Y:y_data})
        if(step % 10 == 0):
            print(step, cost_val, W_val)
    
    print("Prediction", sess.run(pred, feed_dict={X:x_test}))
    print("Accuracy", sess.run(accuracy, feed_dict={X:x_test, Y:y_test}))

0 5.73203 [[ 0.80195683  0.67898041 -1.21691179]
 [-0.30789229 -0.30147803  1.50924742]
 [ 0.75448871 -0.69902533 -2.10733461]]
10 5.48485 [[ 0.79458004  0.68264782 -1.21320236]
 [-0.33509913 -0.28416312  1.51913929]
 [ 0.72715849 -0.68038082 -2.09864902]]
20 5.23864 [[ 0.78722638  0.6862998  -1.20950067]
 [-0.36224121 -0.26688579  1.5290041 ]
 [ 0.69986928 -0.66175956 -2.08998156]]
30 4.99365 [[ 0.77990091  0.68993318 -1.20580852]
 [-0.38930008 -0.24965461  1.53883183]
 [ 0.67263395 -0.6431675  -2.08133864]]
40 4.75026 [[ 0.77261013  0.69354445 -1.20212877]
 [-0.41625008 -0.23248079  1.54860806]
 [ 0.64547074 -0.62461269 -2.07273054]]
50 4.50898 [[ 0.76536208  0.69712871 -1.19846499]
 [-0.4430553  -0.21537915  1.55831158]
 [ 0.6184057  -0.60610634 -2.06417203]]
60 4.27051 [[ 0.7581678   0.70068038 -1.19482231]
 [-0.46966499 -0.19836967  1.56791186]
 [ 0.59147596 -0.58766371 -2.05568504]]
70 4.03585 [[ 0.75104171  0.70419198 -1.191208  ]
 [-0.49600759 -0.18147977  1.57736444]
 [ 0.5647

In [51]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [52]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])
xy = MinMaxScaler(xy)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

x_data[0,1]

0.99999999450549815

In [53]:
X = tf.placeholder("float32", shape=[None,4])
Y = tf.placeholder("float32", shape=[None,1])
W = tf.Variable(tf.random_normal([4,1]), name = 'weight')
b = tf.Variable(tf.random_normal([1]), name = 'bias')

In [54]:
hypo = tf.matmul(X,W) + b
cost = tf.reduce_mean(tf.square(hypo - Y))
train = tf.train.GradientDescentOptimizer(learning_rate=1e-5).minimize(cost)

In [55]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypo, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  1.48743 
Prediction:
 [[-0.93496293]
 [-0.61039644]
 [-0.65905547]
 [-0.7325992 ]
 [-0.68487626]
 [-0.55113161]
 [-0.52954543]
 [-0.33258   ]]
1 Cost:  1.48732 
Prediction:
 [[-0.93490076]
 [-0.61033738]
 [-0.65900624]
 [-0.73256087]
 [-0.68483078]
 [-0.55108786]
 [-0.52951646]
 [-0.33255196]]
2 Cost:  1.48721 
Prediction:
 [[-0.93483865]
 [-0.61027861]
 [-0.65895683]
 [-0.73252255]
 [-0.68478543]
 [-0.55104399]
 [-0.52948749]
 [-0.33252388]]
3 Cost:  1.4871 
Prediction:
 [[-0.93477654]
 [-0.61021948]
 [-0.65890753]
 [-0.7324841 ]
 [-0.68473995]
 [-0.55100012]
 [-0.52945852]
 [-0.33249581]]
4 Cost:  1.48699 
Prediction:
 [[-0.93471426]
 [-0.61016041]
 [-0.65885824]
 [-0.73244584]
 [-0.68469453]
 [-0.55095631]
 [-0.5294295 ]
 [-0.33246776]]
5 Cost:  1.48688 
Prediction:
 [[-0.93465209]
 [-0.61010122]
 [-0.65880883]
 [-0.73240745]
 [-0.68464911]
 [-0.55091262]
 [-0.52940047]
 [-0.33243969]]
6 Cost:  1.48677 
Prediction:
 [[-0.93458998]
 [-0.61004221]
 [-0.65875953]
 [-0.73236901

In [42]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for step in range(2000):
        cost_v, hy_v, _ = sess.run([cost, hypo, train], feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            print(step, "Cost : ", cost_v, "\nPrediction\n", hy_val)

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op 'Placeholder', defined at:
  File "//anaconda/envs/py35/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "//anaconda/envs/py35/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "//anaconda/envs/py35/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "//anaconda/envs/py35/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "//anaconda/envs/py35/lib/python3.5/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "//anaconda/envs/py35/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "//anaconda/envs/py35/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-b9f44d4e7dbd>", line 1, in <module>
    X = tf.placeholder("float", [None, 3])
  File "//anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/array_ops.py", line 1502, in placeholder
    name=name)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2149, in _placeholder
    name=name)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "//anaconda/envs/py35/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
