In [53]:
import tensorflow as tf
import numpy as np
import pprint

tf.set_random_seed(777)  # for reproducibility

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

In [54]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])
t.ndim # rank
t.shape # shape
t[0], t[1], t[-1] # -1 맨 마지막꺼
t[2:5], t[4:-1]
t[:2], t[3:]

(array([ 0.,  1.]), array([ 3.,  4.,  5.,  6.]))

In [55]:
t2 = np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.],[10.,11.,12.]])
t2.ndim # rank = 2
t2.shape


(4, 3)

In [56]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

t = tf.constant([[1,2],
                 [3,4]]) # end braket개수 = rank # 
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [57]:
tf.shape(t).eval()

array([2, 2], dtype=int32)

In [58]:
## 괄호개수 : 4개 -> rank (shape = ( , , , ))
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

# axis = 0
[
    # axis = 1
    [
        # axis = 2
        [
            # axis = 3
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [59]:
    #-->(horizontal) axis 1(오른쪽 방향), vertical --> axis 0(아래쪽 방향) , -1일 경우 가장 안쪽
x = [[1., 2., 3.],
     [3., 4., 5.]]


tf.reduce_mean(x).eval()

3.0

In [60]:
tf.reduce_mean(x,axis = 0).eval()

array([ 2.,  3.,  4.], dtype=float32)

In [61]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
tf.matmul(matrix1, matrix2).eval()

array([[ 12.]], dtype=float32)

In [62]:
tf.shape(matrix1).eval()

array([1, 2], dtype=int32)

In [63]:
(matrix1*matrix2).eval()

array([[ 6.,  6.],
       [ 6.,  6.]], dtype=float32)

In [64]:

t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape
t

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [65]:
t.shape

(2, 2, 3)

In [66]:
tf.reshape(t, shape = [-1,3]).eval() # rank 3으로 알아서 하라는 것
# 3은 원래 것을 그대로 가져옴

tf.reshape(t, shape=[-1,1,3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [67]:
# Removes dimensions of size 1 from the shape of a tensor.
tf.squeeze([[0],[1],[2]]).eval()

array([0, 1, 2], dtype=int32)

In [68]:
tf.expand_dims([0,1,2], 1).eval()

array([[0],
       [1],
       [2]], dtype=int32)

In [69]:
tf.one_hot([[0],[1],[2]], depth = 3).eval()
# rank가 2였는데, 자동으로 하나를 더 늘림

array([[[ 1.,  0.,  0.]],

       [[ 0.,  1.,  0.]],

       [[ 0.,  0.,  1.]]], dtype=float32)

In [70]:
t = tf.one_hot([[0],[1],[2]], depth = 3)
tf.reshape(t, shape=[-1,3]).eval()

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [71]:
tf.cast([1.8,1.2,3.3,4.9], tf.int32).eval()
tf.cast([True, False, 1==1, 0==1], tf.int32).eval()

array([1, 0, 1, 0], dtype=int32)

In [72]:

x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)

In [73]:
tf.stack([x, y, z], axis=-1).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [78]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval() # 같은 모양으로 1로 채우는 것
tf.zeros_like(x).eval() # 같은 모양으로 0로 채우는 것

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [75]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [76]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


In [83]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [82]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [50]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [51]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  3],
        [ 1,  4],
        [ 2,  5]],

       [[ 6,  9],
        [ 7, 10],
        [ 8, 11]]])


In [53]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])
